import type { Animation, EasingType, Expression, EyeColors, EyeParams, Project } from '@/types'
import { hexToRgb565 } from '@/lib/color'

const EASING_ENUM: Record<EasingType, string> = {
  linear: 'EYE_EASE_LINEAR',
  easeIn: 'EYE_EASE_IN',
  easeOut: 'EYE_EASE_OUT',
  easeInOut: 'EYE_EASE_INOUT',
  bounce: 'EYE_EASE_BOUNCE',
  elastic: 'EYE_EASE_ELASTIC',
  bezier: 'EYE_EASE_BEZIER'
}

function toIdentifier(name: string): string {
  const cleaned = name.replace(/[^a-zA-Z0-9]+/g, ' ').trim()
  const parts = cleaned.split(' ').filter(Boolean)
  const pascal = parts.map((w) => w[0].toUpperCase() + w.slice(1)).join('')
  return /^[0-9]/.test(pascal) ? `_${pascal}` : pascal
}

function clampByte(v: number): number {
  return Math.max(-127, Math.min(127, Math.round(v)))
}

function eyeFrameLiteral(params: EyeParams, durationMs: number, easing: EasingType, bezier?: [number, number, number, number]): string {
  const [bx1, by1, bx2, by2] = bezier ?? [42, 0, 58, 100]
  const fields = [
    Math.round(params.width),
    Math.round(params.height),
    Math.round(params.radius),
    clampByte(params.rotation),
    Math.round(params.distance),
    Math.round(params.irisWidth),
    Math.round(params.irisHeight),
    Math.round(params.pupilWidth),
    Math.round(params.pupilHeight),
    clampByte(params.pupilX),
    clampByte(params.pupilY),
    Math.round(params.upperEyelid),
    Math.round(params.lowerEyelid),
    clampByte(params.highlightX),
    clampByte(params.highlightY),
    Math.round(params.highlightSize),
    Math.round(durationMs),
    EASING_ENUM[easing],
    Math.round(bx1),
    Math.round(by1),
    Math.round(bx2),
    Math.round(by2)
  ]
  return `  { ${fields.join(', ')} }`
}

function exportAnimation(anim: Animation): string {
  const ident = toIdentifier(anim.name)
  const lines = anim.keyframes.map((k) => eyeFrameLiteral(k.params, k.duration, k.easing, k.customBezier))
  return [
    `// ${anim.name}${anim.loop ? ' (loops)' : ' (plays once)'}`,
    `const EyeFrame Anim_${ident}[] PROGMEM = {`,
    lines.join(',\n'),
    `};`,
    `const uint16_t Anim_${ident}_count = ${anim.keyframes.length};`,
    `const bool Anim_${ident}_loop = ${anim.loop ? 'true' : 'false'};`
  ].join('\n')
}

function exportExpression(expr: Expression): string {
  const ident = toIdentifier(expr.name)
  return `const EyeFrame Expr_${ident} PROGMEM = \n${eyeFrameLiteral(expr.params, 0, 'linear')};`
}

function toRgb565Hex(hex: string): string {
  return `0x${hexToRgb565(hex).toString(16).toUpperCase().padStart(4, '0')}`
}

function exportColors(colors: EyeColors): string {
  return [
    `#define EYE_COLOR_SCLERA    ${toRgb565Hex(colors.sclera)} // RGB565`,
    `#define EYE_COLOR_IRIS      ${toRgb565Hex(colors.iris)}`,
    `#define EYE_COLOR_PUPIL     ${toRgb565Hex(colors.pupil)}`,
    `#define EYE_COLOR_HIGHLIGHT ${toRgb565Hex(colors.highlight)}`,
    `#define EYE_COLOR_SHADOW    ${toRgb565Hex(colors.shadow)}  // shadow arc, intensity ${Math.round(colors.shadowIntensity)}% (not encodable in RGB565 — blend in software)`,
    `#define EYE_COLOR_GLOW      ${toRgb565Hex(colors.glow)}  // outer glow, intensity ${Math.round(colors.glowIntensity)}%`
  ].join('\n')
}

export function generateCppHeader(project: Project): string {
  const guard = `KIBO_EYE_ANIMATIONS_${toIdentifier(project.name).toUpperCase() || 'PROJECT'}_H`
  const header = `/*
 * Generated by Kibo Eye Studio — do not hand-edit, re-export instead.
 * Project: ${project.name}
 * Generated: ${new Date().toISOString()}
 *
 * Field order in EyeFrame matches the studio's EyeParams model:
 *   width, height, radius, rotation, distance, irisWidth, irisHeight, pupilWidth,
 *   pupilHeight, pupilX, pupilY, upperEyelid, lowerEyelid, highlightX, highlightY,
 *   highlightSize, durationMs, easing, bezierX1, bezierY1, bezierX2, bezierY2
 * (bezier fields only matter when easing == EYE_EASE_BEZIER, scaled 0-100)
 *
 * Eye colors are exported below as RGB565 #defines (sclera/iris/pupil/highlight/shadow/
 * glow) matching the studio's Color panel — draw the iris disc, then the pupil disc, then
 * blend the highlight/shadow/glow layers with those constants in your own draw routine.
 *
 * Usage sketch (pseudo-code — write your own player loop against your display driver):
 *   float t = elapsedMs / (float)frame.durationMs;               // 0..1 within the segment
 *   t = applyEasing(t, frame.easing, frame.bezierX1, ...);        // ease the same curve types
 *   EyeParams live = lerp(prevFrame, frame, t);                   // interpolate every field
 *   drawEyePair(live);                                            // your GC9A01 draw routine
 */
#ifndef ${guard}
#define ${guard}

#include <stdint.h>
#if defined(__AVR__)
#include <avr/pgmspace.h> // only classic AVR boards need this; ESP32/ESP8266/SAMD/RP2040 cores already define PROGMEM
#endif

enum EyeEasing : uint8_t {
  EYE_EASE_LINEAR = 0,
  EYE_EASE_IN,
  EYE_EASE_OUT,
  EYE_EASE_INOUT,
  EYE_EASE_BOUNCE,
  EYE_EASE_ELASTIC,
  EYE_EASE_BEZIER
};

struct EyeFrame {
  uint8_t width, height, radius;
  int8_t rotation;
  uint8_t distance;
  uint8_t irisWidth, irisHeight;
  uint8_t pupilWidth, pupilHeight;
  int8_t pupilX, pupilY;
  uint8_t upperEyelid, lowerEyelid;
  int8_t highlightX, highlightY;
  uint8_t highlightSize;
  uint16_t durationMs;
  uint8_t easing;
  int8_t bezierX1, bezierY1, bezierX2, bezierY2;
};

// ---- Colors -----------------------------------------------------------

${exportColors(project.colors)}

// ---- Animations -----------------------------------------------------------

${project.animations.map(exportAnimation).join('\n\n')}

// ---- Expressions (static poses) -------------------------------------------

${project.expressions.map(exportExpression).join('\n\n')}

#endif // ${guard}
`
  return header
}
